[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[build]
  base = "frontend"
  publish = "build"
  command = "npm install --legacy-peer-deps && npm run build"

[functions]
  directory = "frontend/netlify/functions"
